server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/postgres
    driverClassName: org.postgresql.Driver
    user: postgres
    password: password
  jooq:
    sql-dialect: H2Dialect


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
