spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: service-security
          uri: ${SECURITY_HOST:http://localhost:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
